server:
  port: 8013

spring:
  application:
    name: nacos-product
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 130.252.102.241:8848
        register-enabled: true