#port端口配置
server:
  port: 8081

#spring相关配置
spring:
  #服务名
  application:
    name: order-service
  #数据源配置，需要预先创建shop-order数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  #JPA持久层框架配置
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #服务注册到Nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#Seata分布式事务配置(AT模式)
seata:
  enabled: true
  application-id: ${spring.application.name}
  #客户端和服务端在同一个事务组
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: file
#    nacos:
#      namespace:
#      serverAddr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      username: "nacos"
#      password: "nacos"
  #服务注册到nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"

#Ribbon超时设置
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

#配置让所有 FeignClient，使用FeignRequestInterceptor
#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#        requestInterceptors: com.example.order.config.FeignRequestInterceptor
#修改默认隔离策略为信号量模式
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
