##=========服务生产者-会员服务配置========
##服务在7777端口暴露出来
server:
  port: 8765

##配置Spring相关
spring:
  ##应用服务名称,切记不能为下划线consul_member_provider，因为Feign不支持
  application:
    name: consul-member-provider
  ##consul注册中心地址
  cloud:
    consul:
      ##Consul所在主机ip
      host: localhost
      ##Consul监听的端口
      port: 8500
      discovery:
        ##配置开启服务注册到Consul上
        register: true
        ##配置注册到Consul的服务实例名称(Consul里Feign是通过此名称调用，而非spring.application.name)
        service-name: member-provider
        ##配置服务健康检查地址，供Consul调用
        healthCheckPath: /health
        ##Consul 健康检查频率
        healthCheckInterval: 15s





